### ISSUE TITLE
problem in checking ETag key

### ISSUE THREAD

**Issue by ricksondpenha** [ksitko/Secure-OTA#1]
Hi,
I've created a AWS S3 account and placed my firmware.bin file in the bucket, updated the path for the bucket in menuconfig, all goes fine.. It even connects to the s3 bucket but i get a error saying 
`ota_validate: Cannot find ETag key!`
`ota_validate: Cannot find binary length key!`

Do i have to upload another file calculating the md5 checksum of the remote binary file?

Can you give me the procedure for updating the remote bin file in s3.. I have configured my s3 bucket to forward http responses to https using cloudwatch. whatelse do i need to do on the cloudend

**Comment by ksitko** [comment]
ricksondpenha,

I haven't worked on ESP32's for a while, but let me try my best.

You do not need a separate file. Secure-OTA takes the header information which AWS S3 generates for your firmware.bin. The Etag value from the headers is the MD5 sum of the file [if the file was uploaded as described in the S3 docs](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html). Once Secure-OTA finds this it calculates the MD5 sum of your current partition and if the two are different, it selects a different partition, downloads it to that partition, calculates the MD5 sum of the new partition to ensure it downloaded correctly and if the MD5sums match then it sets that partition as the new current partition and reboots. 

Going back to your error - are you certain it is connecting to your S3 bucket? Your firmware file may not be correctly set to public.

To make sure it is correctly set and visible, try the following command in terminal:

`curl -I https://s3.amazonaws.com/YourS3bucket/YourFilePath/YourFirmware.bin`

You can find the precise link to use by checking the overview of your firmware file on S3.

**Comment by ksitko** [comment]
I just found that the TLS request was hard coded to test the program. I have fixed that in c0da2772cbd002ef2558b81fa9982dc2ca0c9693.
